export const USER_EMAIL_LENGTH = 255
export const USER_USERNAME_LENGTH = 30
export const USER_LEGAL_FULL_NAME_LENGTH = 50
export const USER_DISPLAY_NAME_LENGTH = 50
export const USER_PHONE_NUMBER_LENGTH = 30
export const USER_COUNTRY_CODE_LENGTH = 3
