defaultSemverRangePrefix: ""

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

# Removes "can't be found in the cache" logs
logFilters:
- code: YN0013
  level: discard
