version: "3.8"

services:
  database:
    # Should match AWS Aurora Postgres version:
    # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraPostgreSQL.Updates.html#AuroraPostgreSQL.Updates.20180305.136X
    image: postgres:13.6-alpine
    ports:
      - 5432:${POSTGRES_PORT:-5432}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-moment}
    volumes:
      - postgres:/var/lib/postgresql/data
  # Should match the AWS Redis version:
  # https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html
  redis:
    image: redis:6.2.7-alpine
    command: redis-server
    ports:
      - 6379:${REDIS_PORT:-6379}
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
