/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddListMemberDto
 */
export interface AddListMemberDto {
    /**
     * 
     * @type {string}
     * @memberof AddListMemberDto
     */
    list: string;
    /**
     * 
     * @type {string}
     * @memberof AddListMemberDto
     */
    user: string;
}

export function AddListMemberDtoFromJSON(json: any): AddListMemberDto {
    return AddListMemberDtoFromJSONTyped(json, false);
}

export function AddListMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddListMemberDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'list': json['list'],
        'user': json['user'],
    };
}

export function AddListMemberDtoToJSON(value?: AddListMemberDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'list': value.list,
        'user': value.user,
    };
}

