/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentDto
 */
export interface CommentDto {
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    commentId: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    commenterId: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    commenterUsername: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentDto
     */
    createdAt: Date;
}

export function CommentDtoFromJSON(json: any): CommentDto {
    return CommentDtoFromJSONTyped(json, false);
}

export function CommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': json['commentId'],
        'postId': json['postId'],
        'commenterId': json['commenterId'],
        'content': json['content'],
        'commenterUsername': json['commenterUsername'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CommentDtoToJSON(value?: CommentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentId': value.commentId,
        'postId': value.postId,
        'commenterId': value.commenterId,
        'content': value.content,
        'commenterUsername': value.commenterUsername,
        'createdAt': (value.createdAt.toISOString()),
    };
}

