/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSolNftRequestDto
 */
export interface CreateSolNftRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSolNftRequestDto
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSolNftRequestDto
     */
    walletId: string;
}

export function CreateSolNftRequestDtoFromJSON(json: any): CreateSolNftRequestDto {
    return CreateSolNftRequestDtoFromJSONTyped(json, false);
}

export function CreateSolNftRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSolNftRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'walletId': json['walletId'],
    };
}

export function CreateSolNftRequestDtoToJSON(value?: CreateSolNftRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'collectionId': value.collectionId,
        'walletId': value.walletId,
    };
}

