/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    content: string;
}

export function CreateCommentDtoFromJSON(json: any): CreateCommentDto {
    return CreateCommentDtoFromJSONTyped(json, false);
}

export function CreateCommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'content': json['content'],
    };
}

export function CreateCommentDtoToJSON(value?: CreateCommentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postId': value.postId,
        'content': value.content,
    };
}

