/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLocalUserRequestDto
 */
export interface CreateLocalUserRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLocalUserRequestDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLocalUserRequestDto
     */
    password: string;
}

/**
 * Check if a given object implements the CreateLocalUserRequestDto interface.
 */
export function instanceOfCreateLocalUserRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function CreateLocalUserRequestDtoFromJSON(json: any): CreateLocalUserRequestDto {
    return CreateLocalUserRequestDtoFromJSONTyped(json, false);
}

export function CreateLocalUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLocalUserRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function CreateLocalUserRequestDtoToJSON(value?: CreateLocalUserRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

