/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWalletRequestDto
 */
export interface CreateWalletRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateWalletRequestDto
     */
    signedMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletRequestDto
     */
    rawMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletRequestDto
     */
    walletAddress: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletRequestDto
     */
    chain: CreateWalletRequestDtoChainEnum;
}


/**
 * @export
 */
export const CreateWalletRequestDtoChainEnum = {
    Eth: 'eth',
    Sol: 'sol',
    Avax: 'avax',
    Matic: 'matic'
} as const;
export type CreateWalletRequestDtoChainEnum = typeof CreateWalletRequestDtoChainEnum[keyof typeof CreateWalletRequestDtoChainEnum];


/**
 * Check if a given object implements the CreateWalletRequestDto interface.
 */
export function instanceOfCreateWalletRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "signedMessage" in value;
    isInstance = isInstance && "rawMessage" in value;
    isInstance = isInstance && "walletAddress" in value;
    isInstance = isInstance && "chain" in value;

    return isInstance;
}

export function CreateWalletRequestDtoFromJSON(json: any): CreateWalletRequestDto {
    return CreateWalletRequestDtoFromJSONTyped(json, false);
}

export function CreateWalletRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWalletRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'signedMessage': json['signedMessage'],
        'rawMessage': json['rawMessage'],
        'walletAddress': json['walletAddress'],
        'chain': json['chain'],
    };
}

export function CreateWalletRequestDtoToJSON(value?: CreateWalletRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'signedMessage': value.signedMessage,
        'rawMessage': value.rawMessage,
        'walletAddress': value.walletAddress,
        'chain': value.chain,
    };
}

