/* tslint:disable */
/* eslint-disable */
/**
 * Moment Backend
 * Be in the moment
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEthNftCollectionDto
 */
export interface CreateEthNftCollectionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateEthNftCollectionDto
     */
    tokenAddress: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEthNftCollectionDto
     */
    name: string;
}

export function CreateEthNftCollectionDtoFromJSON(json: any): CreateEthNftCollectionDto {
    return CreateEthNftCollectionDtoFromJSONTyped(json, false);
}

export function CreateEthNftCollectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEthNftCollectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenAddress': json['tokenAddress'],
        'name': json['name'],
    };
}

export function CreateEthNftCollectionDtoToJSON(value?: CreateEthNftCollectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenAddress': value.tokenAddress,
        'name': value.name,
    };
}

