/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditPostCategoryRequestDto
 */
export interface EditPostCategoryRequestDto {
    /**
     * 
     * @type {string}
     * @memberof EditPostCategoryRequestDto
     */
    postCategoryId: string;
    /**
     * 
     * @type {string}
     * @memberof EditPostCategoryRequestDto
     */
    name: string;
}

/**
 * Check if a given object implements the EditPostCategoryRequestDto interface.
 */
export function instanceOfEditPostCategoryRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "postCategoryId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function EditPostCategoryRequestDtoFromJSON(json: any): EditPostCategoryRequestDto {
    return EditPostCategoryRequestDtoFromJSONTyped(json, false);
}

export function EditPostCategoryRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditPostCategoryRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postCategoryId': json['postCategoryId'],
        'name': json['name'],
    };
}

export function EditPostCategoryRequestDtoToJSON(value?: EditPostCategoryRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postCategoryId': value.postCategoryId,
        'name': value.name,
    };
}

