/* tslint:disable */
/* eslint-disable */
/**
 * Moment Backend
 * Be in the moment
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GemPackageEntityDto,
    GemPackageEntityDtoFromJSON,
    GemPackageEntityDtoFromJSONTyped,
    GemPackageEntityDtoToJSON,
} from './GemPackageEntityDto';

/**
 * 
 * @export
 * @interface GemPackagesDto
 */
export interface GemPackagesDto {
    /**
     * 
     * @type {Array<GemPackageEntityDto>}
     * @memberof GemPackagesDto
     */
    packages: Array<GemPackageEntityDto>;
}

export function GemPackagesDtoFromJSON(json: any): GemPackagesDto {
    return GemPackagesDtoFromJSONTyped(json, false);
}

export function GemPackagesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GemPackagesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'packages': ((json['packages'] as Array<any>).map(GemPackageEntityDtoFromJSON)),
    };
}

export function GemPackagesDtoToJSON(value?: GemPackagesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'packages': ((value.packages as Array<any>).map(GemPackageEntityDtoToJSON)),
    };
}

