/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCommentsForPostRequesteDto
 */
export interface GetCommentsForPostRequesteDto {
    /**
     * 
     * @type {Date}
     * @memberof GetCommentsForPostRequesteDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsForPostRequesteDto
     */
    lastId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsForPostRequesteDto
     */
    postId: string;
}

/**
 * Check if a given object implements the GetCommentsForPostRequesteDto interface.
 */
export function instanceOfGetCommentsForPostRequesteDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "postId" in value;

    return isInstance;
}

export function GetCommentsForPostRequesteDtoFromJSON(json: any): GetCommentsForPostRequesteDto {
    return GetCommentsForPostRequesteDtoFromJSONTyped(json, false);
}

export function GetCommentsForPostRequesteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCommentsForPostRequesteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'postId': json['postId'],
    };
}

export function GetCommentsForPostRequesteDtoToJSON(value?: GetCommentsForPostRequesteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'lastId': value.lastId,
        'postId': value.postId,
    };
}

