/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCreatorSettingsResponseDto
 */
export interface GetCreatorSettingsResponseDto {
    /**
     * 
     * @type {number}
     * @memberof GetCreatorSettingsResponseDto
     */
    minimumTipAmount: number;
    /**
     * 
     * @type {string}
     * @memberof GetCreatorSettingsResponseDto
     */
    payoutFrequency: GetCreatorSettingsResponseDtoPayoutFrequencyEnum;
    /**
     * 
     * @type {string}
     * @memberof GetCreatorSettingsResponseDto
     */
    welcomeMessage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetCreatorSettingsResponseDto
     */
    allowCommentsOnPosts?: boolean;
}


/**
 * @export
 */
export const GetCreatorSettingsResponseDtoPayoutFrequencyEnum = {
    Manual: 'manual',
    TwoWeeks: 'two weeks',
    OneWeek: 'one week'
} as const;
export type GetCreatorSettingsResponseDtoPayoutFrequencyEnum = typeof GetCreatorSettingsResponseDtoPayoutFrequencyEnum[keyof typeof GetCreatorSettingsResponseDtoPayoutFrequencyEnum];


export function GetCreatorSettingsResponseDtoFromJSON(json: any): GetCreatorSettingsResponseDto {
    return GetCreatorSettingsResponseDtoFromJSONTyped(json, false);
}

export function GetCreatorSettingsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCreatorSettingsResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minimumTipAmount': json['minimumTipAmount'],
        'payoutFrequency': json['payoutFrequency'],
        'welcomeMessage': !exists(json, 'welcomeMessage') ? undefined : json['welcomeMessage'],
        'allowCommentsOnPosts': !exists(json, 'allowCommentsOnPosts') ? undefined : json['allowCommentsOnPosts'],
    };
}

export function GetCreatorSettingsResponseDtoToJSON(value?: GetCreatorSettingsResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'minimumTipAmount': value.minimumTipAmount,
        'payoutFrequency': value.payoutFrequency,
        'welcomeMessage': value.welcomeMessage,
        'allowCommentsOnPosts': value.allowCommentsOnPosts,
    };
}

