/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChannelResponseDto
 */
export interface GetChannelResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GetChannelResponseDto
     */
    channelId: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetChannelResponseDto
     */
    blocked: boolean;
}

/**
 * Check if a given object implements the GetChannelResponseDto interface.
 */
export function instanceOfGetChannelResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelId" in value;
    isInstance = isInstance && "blocked" in value;

    return isInstance;
}

export function GetChannelResponseDtoFromJSON(json: any): GetChannelResponseDto {
    return GetChannelResponseDtoFromJSONTyped(json, false);
}

export function GetChannelResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChannelResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'blocked': json['blocked'],
    };
}

export function GetChannelResponseDtoToJSON(value?: GetChannelResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelId': value.channelId,
        'blocked': value.blocked,
    };
}

