/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCircleCardResponseDto
 */
export interface GetCircleCardResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GetCircleCardResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetCircleCardResponseDto
     */
    circleCardId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCircleCardResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GetCircleCardResponseDto
     */
    firstDigit: string;
    /**
     * 
     * @type {string}
     * @memberof GetCircleCardResponseDto
     */
    fourDigits: string;
    /**
     * 
     * @type {number}
     * @memberof GetCircleCardResponseDto
     */
    expMonth: number;
    /**
     * 
     * @type {number}
     * @memberof GetCircleCardResponseDto
     */
    expYear: number;
    /**
     * 
     * @type {string}
     * @memberof GetCircleCardResponseDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetCircleCardResponseDto
     */
    active: boolean;
}

export function GetCircleCardResponseDtoFromJSON(json: any): GetCircleCardResponseDto {
    return GetCircleCardResponseDtoFromJSONTyped(json, false);
}

export function GetCircleCardResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCircleCardResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'circleCardId': !exists(json, 'circleCardId') ? undefined : json['circleCardId'],
        'status': json['status'],
        'firstDigit': json['firstDigit'],
        'fourDigits': json['fourDigits'],
        'expMonth': json['expMonth'],
        'expYear': json['expYear'],
        'name': json['name'],
        'active': json['active'],
    };
}

export function GetCircleCardResponseDtoToJSON(value?: GetCircleCardResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'circleCardId': value.circleCardId,
        'status': value.status,
        'firstDigit': value.firstDigit,
        'fourDigits': value.fourDigits,
        'expMonth': value.expMonth,
        'expYear': value.expYear,
        'name': value.name,
        'active': value.active,
    };
}

