/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEthNftCollectionResponseDto
 */
export interface GetEthNftCollectionResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GetEthNftCollectionResponseDto
     */
    tokenAddress: string;
    /**
     * 
     * @type {string}
     * @memberof GetEthNftCollectionResponseDto
     */
    name: string;
}

export function GetEthNftCollectionResponseDtoFromJSON(json: any): GetEthNftCollectionResponseDto {
    return GetEthNftCollectionResponseDtoFromJSONTyped(json, false);
}

export function GetEthNftCollectionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEthNftCollectionResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenAddress': json['tokenAddress'],
        'name': json['name'],
    };
}

export function GetEthNftCollectionResponseDtoToJSON(value?: GetEthNftCollectionResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenAddress': value.tokenAddress,
        'name': value.name,
    };
}

