/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostDto } from './PostDto';
import {
    PostDtoFromJSON,
    PostDtoFromJSONTyped,
    PostDtoToJSON,
} from './PostDto';

/**
 * 
 * @export
 * @interface GetFeedResponseDto
 */
export interface GetFeedResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GetFeedResponseDto
     */
    lastId: string;
    /**
     * 
     * @type {Date}
     * @memberof GetFeedResponseDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetFeedResponseDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<PostDto>}
     * @memberof GetFeedResponseDto
     */
    posts: Array<PostDto>;
    /**
     * 
     * @type {number}
     * @memberof GetFeedResponseDto
     */
    count: number;
}

/**
 * Check if a given object implements the GetFeedResponseDto interface.
 */
export function instanceOfGetFeedResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastId" in value;
    isInstance = isInstance && "posts" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function GetFeedResponseDtoFromJSON(json: any): GetFeedResponseDto {
    return GetFeedResponseDtoFromJSONTyped(json, false);
}

export function GetFeedResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeedResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastId': json['lastId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'posts': ((json['posts'] as Array<any>).map(PostDtoFromJSON)),
        'count': json['count'],
    };
}

export function GetFeedResponseDtoToJSON(value?: GetFeedResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastId': value.lastId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'posts': ((value.posts as Array<any>).map(PostDtoToJSON)),
        'count': value.count,
    };
}

