/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFollowingResponseDto
 */
export interface GetFollowingResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GetFollowingResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetFollowingResponseDto
     */
    followerId: string;
    /**
     * 
     * @type {string}
     * @memberof GetFollowingResponseDto
     */
    creatorId: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetFollowingResponseDto
     */
    isActive: boolean;
}

export function GetFollowingResponseDtoFromJSON(json: any): GetFollowingResponseDto {
    return GetFollowingResponseDtoFromJSONTyped(json, false);
}

export function GetFollowingResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFollowingResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'followerId': json['followerId'],
        'creatorId': json['creatorId'],
        'isActive': json['isActive'],
    };
}

export function GetFollowingResponseDtoToJSON(value?: GetFollowingResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'followerId': value.followerId,
        'creatorId': value.creatorId,
        'isActive': value.isActive,
    };
}

