/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetPostDto,
    GetPostDtoFromJSON,
    GetPostDtoFromJSONTyped,
    GetPostDtoToJSON,
} from './GetPostDto';

/**
 * 
 * @export
 * @interface GetFeedDto
 */
export interface GetFeedDto {
    /**
     * 
     * @type {Array<GetPostDto>}
     * @memberof GetFeedDto
     */
    posts: Array<GetPostDto>;
    /**
     * 
     * @type {number}
     * @memberof GetFeedDto
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof GetFeedDto
     */
    cursor: string;
}

export function GetFeedDtoFromJSON(json: any): GetFeedDto {
    return GetFeedDtoFromJSONTyped(json, false);
}

export function GetFeedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeedDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'posts': ((json['posts'] as Array<any>).map(GetPostDtoFromJSON)),
        'count': json['count'],
        'cursor': json['cursor'],
    };
}

export function GetFeedDtoToJSON(value?: GetFeedDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'posts': ((value.posts as Array<any>).map(GetPostDtoToJSON)),
        'count': value.count,
        'cursor': value.cursor,
    };
}

