/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetListsRequestsDto
 */
export interface GetListsRequestsDto {
    /**
     * 
     * @type {Date}
     * @memberof GetListsRequestsDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetListsRequestsDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetListsRequestsDto
     */
    lastId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetListsRequestsDto
     */
    search?: string;
    /**
     * 
     * @type {string}
     * @memberof GetListsRequestsDto
     */
    order: string;
    /**
     * 
     * @type {string}
     * @memberof GetListsRequestsDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetListsRequestsDto
     */
    orderType: GetListsRequestsDtoOrderTypeEnum;
}


/**
 * @export
 */
export const GetListsRequestsDtoOrderTypeEnum = {
    Name: 'name',
    UpdatedAt: 'updated at',
    CreatedAt: 'created at'
} as const;
export type GetListsRequestsDtoOrderTypeEnum = typeof GetListsRequestsDtoOrderTypeEnum[keyof typeof GetListsRequestsDtoOrderTypeEnum];


/**
 * Check if a given object implements the GetListsRequestsDto interface.
 */
export function instanceOfGetListsRequestsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "orderType" in value;

    return isInstance;
}

export function GetListsRequestsDtoFromJSON(json: any): GetListsRequestsDto {
    return GetListsRequestsDtoFromJSONTyped(json, false);
}

export function GetListsRequestsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListsRequestsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'search': !exists(json, 'search') ? undefined : json['search'],
        'order': json['order'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'orderType': json['orderType'],
    };
}

export function GetListsRequestsDtoToJSON(value?: GetListsRequestsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'lastId': value.lastId,
        'search': value.search,
        'order': value.order,
        'name': value.name,
        'orderType': value.orderType,
    };
}

