/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetListResponseDto
 */
export interface GetListResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GetListResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetListResponseDto
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetListResponseDto
     */
    listMembers: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GetListResponseDto
     */
    size: number;
}

export function GetListResponseDtoFromJSON(json: any): GetListResponseDto {
    return GetListResponseDtoFromJSONTyped(json, false);
}

export function GetListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'listMembers': json['listMembers'],
        'size': json['size'],
    };
}

export function GetListResponseDtoToJSON(value?: GetListResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'listMembers': value.listMembers,
        'size': value.size,
    };
}

