/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListMemberDto } from './ListMemberDto';
import {
    ListMemberDtoFromJSON,
    ListMemberDtoFromJSONTyped,
    ListMemberDtoToJSON,
} from './ListMemberDto';

/**
 * 
 * @export
 * @interface GetListMembersResponseDto
 */
export interface GetListMembersResponseDto {
    /**
     * 
     * @type {Array<ListMemberDto>}
     * @memberof GetListMembersResponseDto
     */
    listMembers: Array<ListMemberDto>;
}

/**
 * Check if a given object implements the GetListMembersResponseDto interface.
 */
export function instanceOfGetListMembersResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "listMembers" in value;

    return isInstance;
}

export function GetListMembersResponseDtoFromJSON(json: any): GetListMembersResponseDto {
    return GetListMembersResponseDtoFromJSONTyped(json, false);
}

export function GetListMembersResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListMembersResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listMembers': ((json['listMembers'] as Array<any>).map(ListMemberDtoFromJSON)),
    };
}

export function GetListMembersResponseDtoToJSON(value?: GetListMembersResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listMembers': ((value.listMembers as Array<any>).map(ListMemberDtoToJSON)),
    };
}

