/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetListsResponseDto
 */
export interface GetListsResponseDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetListsResponseDto
     */
    lists: Array<string>;
}

/**
 * Check if a given object implements the GetListsResponseDto interface.
 */
export function instanceOfGetListsResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lists" in value;

    return isInstance;
}

export function GetListsResponseDtoFromJSON(json: any): GetListsResponseDto {
    return GetListsResponseDtoFromJSONTyped(json, false);
}

export function GetListsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListsResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lists': json['lists'],
    };
}

export function GetListsResponseDtoToJSON(value?: GetListsResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lists': value.lists,
    };
}

