/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMessageBuyersRequestDto
 */
export interface GetMessageBuyersRequestDto {
    /**
     * 
     * @type {string}
     * @memberof GetMessageBuyersRequestDto
     */
    lastId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMessageBuyersRequestDto
     */
    search?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMessageBuyersRequestDto
     */
    paidMessageId: string;
    /**
     * 
     * @type {Date}
     * @memberof GetMessageBuyersRequestDto
     */
    paidAt?: Date;
}

/**
 * Check if a given object implements the GetMessageBuyersRequestDto interface.
 */
export function instanceOfGetMessageBuyersRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "paidMessageId" in value;

    return isInstance;
}

export function GetMessageBuyersRequestDtoFromJSON(json: any): GetMessageBuyersRequestDto {
    return GetMessageBuyersRequestDtoFromJSONTyped(json, false);
}

export function GetMessageBuyersRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMessageBuyersRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'search': !exists(json, 'search') ? undefined : json['search'],
        'paidMessageId': json['paidMessageId'],
        'paidAt': !exists(json, 'paidAt') ? undefined : (new Date(json['paidAt'])),
    };
}

export function GetMessageBuyersRequestDtoToJSON(value?: GetMessageBuyersRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastId': value.lastId,
        'search': value.search,
        'paidMessageId': value.paidMessageId,
        'paidAt': value.paidAt === undefined ? undefined : (value.paidAt.toISOString()),
    };
}

