/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPostsRequesteDto
 */
export interface GetPostsRequesteDto {
    /**
     * 
     * @type {Date}
     * @memberof GetPostsRequesteDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetPostsRequesteDto
     */
    lastId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetPostsRequesteDto
     */
    scheduledOnly: boolean;
}

/**
 * Check if a given object implements the GetPostsRequesteDto interface.
 */
export function instanceOfGetPostsRequesteDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "scheduledOnly" in value;

    return isInstance;
}

export function GetPostsRequesteDtoFromJSON(json: any): GetPostsRequesteDto {
    return GetPostsRequesteDtoFromJSONTyped(json, false);
}

export function GetPostsRequesteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostsRequesteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'scheduledOnly': json['scheduledOnly'],
    };
}

export function GetPostsRequesteDtoToJSON(value?: GetPostsRequesteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'lastId': value.lastId,
        'scheduledOnly': value.scheduledOnly,
    };
}

