/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaidMessageDto } from './PaidMessageDto';
import {
    PaidMessageDtoFromJSON,
    PaidMessageDtoFromJSONTyped,
    PaidMessageDtoToJSON,
} from './PaidMessageDto';

/**
 * 
 * @export
 * @interface GetPaidMessagesResponseDto
 */
export interface GetPaidMessagesResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof GetPaidMessagesResponseDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetPaidMessagesResponseDto
     */
    lastId?: string;
    /**
     * 
     * @type {Array<PaidMessageDto>}
     * @memberof GetPaidMessagesResponseDto
     */
    data: Array<PaidMessageDto>;
}

/**
 * Check if a given object implements the GetPaidMessagesResponseDto interface.
 */
export function instanceOfGetPaidMessagesResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetPaidMessagesResponseDtoFromJSON(json: any): GetPaidMessagesResponseDto {
    return GetPaidMessagesResponseDtoFromJSONTyped(json, false);
}

export function GetPaidMessagesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaidMessagesResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'data': ((json['data'] as Array<any>).map(PaidMessageDtoFromJSON)),
    };
}

export function GetPaidMessagesResponseDtoToJSON(value?: GetPaidMessagesResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'lastId': value.lastId,
        'data': ((value.data as Array<any>).map(PaidMessageDtoToJSON)),
    };
}

