/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPostCategoriesRequestDto
 */
export interface GetPostCategoriesRequestDto {
    /**
     * 
     * @type {string}
     * @memberof GetPostCategoriesRequestDto
     */
    userId: string;
}

/**
 * Check if a given object implements the GetPostCategoriesRequestDto interface.
 */
export function instanceOfGetPostCategoriesRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function GetPostCategoriesRequestDtoFromJSON(json: any): GetPostCategoriesRequestDto {
    return GetPostCategoriesRequestDtoFromJSONTyped(json, false);
}

export function GetPostCategoriesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostCategoriesRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function GetPostCategoriesRequestDtoToJSON(value?: GetPostCategoriesRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

