/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPostsRequestDto
 */
export interface GetPostsRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof GetPostsRequestDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetPostsRequestDto
     */
    lastId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetPostsRequestDto
     */
    scheduledOnly: boolean;
}

/**
 * Check if a given object implements the GetPostsRequestDto interface.
 */
export function instanceOfGetPostsRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "scheduledOnly" in value;

    return isInstance;
}

export function GetPostsRequestDtoFromJSON(json: any): GetPostsRequestDto {
    return GetPostsRequestDtoFromJSONTyped(json, false);
}

export function GetPostsRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostsRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'scheduledOnly': json['scheduledOnly'],
    };
}

export function GetPostsRequestDtoToJSON(value?: GetPostsRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'lastId': value.lastId,
        'scheduledOnly': value.scheduledOnly,
    };
}

