/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPayinsRequestDto
 */
export interface GetPayinsRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof GetPayinsRequestDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetPayinsRequestDto
     */
    lastId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetPayinsRequestDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetPayinsRequestDto
     */
    endDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GetPayinsRequestDto
     */
    inProgress?: boolean;
}

/**
 * Check if a given object implements the GetPayinsRequestDto interface.
 */
export function instanceOfGetPayinsRequestDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPayinsRequestDtoFromJSON(json: any): GetPayinsRequestDto {
    return GetPayinsRequestDtoFromJSONTyped(json, false);
}

export function GetPayinsRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPayinsRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'inProgress': !exists(json, 'inProgress') ? undefined : json['inProgress'],
    };
}

export function GetPayinsRequestDtoToJSON(value?: GetPayinsRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'lastId': value.lastId,
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'inProgress': value.inProgress,
    };
}

