/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProfileFeedRequestDto
 */
export interface GetProfileFeedRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof GetProfileFeedRequestDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetProfileFeedRequestDto
     */
    lastId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileFeedRequestDto
     */
    pinned?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetProfileFeedRequestDto
     */
    creatorId: string;
}

/**
 * Check if a given object implements the GetProfileFeedRequestDto interface.
 */
export function instanceOfGetProfileFeedRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "creatorId" in value;

    return isInstance;
}

export function GetProfileFeedRequestDtoFromJSON(json: any): GetProfileFeedRequestDto {
    return GetProfileFeedRequestDtoFromJSONTyped(json, false);
}

export function GetProfileFeedRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileFeedRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
        'pinned': !exists(json, 'pinned') ? undefined : json['pinned'],
        'creatorId': json['creatorId'],
    };
}

export function GetProfileFeedRequestDtoToJSON(value?: GetProfileFeedRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'lastId': value.lastId,
        'pinned': value.pinned,
        'creatorId': value.creatorId,
    };
}

