/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSignedUrlDto
 */
export interface GetSignedUrlDto {
    /**
     * 
     * @type {string}
     * @memberof GetSignedUrlDto
     */
    url: string;
}

export function GetSignedUrlDtoFromJSON(json: any): GetSignedUrlDto {
    return GetSignedUrlDtoFromJSONTyped(json, false);
}

export function GetSignedUrlDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSignedUrlDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function GetSignedUrlDtoToJSON(value?: GetSignedUrlDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

