/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsFollowingDto
 */
export interface IsFollowingDto {
    /**
     * 
     * @type {boolean}
     * @memberof IsFollowingDto
     */
    isFollowing: boolean;
}

/**
 * Check if a given object implements the IsFollowingDto interface.
 */
export function instanceOfIsFollowingDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isFollowing" in value;

    return isInstance;
}

export function IsFollowingDtoFromJSON(json: any): IsFollowingDto {
    return IsFollowingDtoFromJSONTyped(json, false);
}

export function IsFollowingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsFollowingDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isFollowing': json['isFollowing'],
    };
}

export function IsFollowingDtoToJSON(value?: IsFollowingDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isFollowing': value.isFollowing,
    };
}

