/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkProcessedRequestDto
 */
export interface MarkProcessedRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MarkProcessedRequestDto
     */
    contentId: string;
    /**
     * 
     * @type {string}
     * @memberof MarkProcessedRequestDto
     */
    userId: string;
}

/**
 * Check if a given object implements the MarkProcessedRequestDto interface.
 */
export function instanceOfMarkProcessedRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contentId" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function MarkProcessedRequestDtoFromJSON(json: any): MarkProcessedRequestDto {
    return MarkProcessedRequestDtoFromJSONTyped(json, false);
}

export function MarkProcessedRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkProcessedRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentId': json['contentId'],
        'userId': json['userId'],
    };
}

export function MarkProcessedRequestDtoToJSON(value?: MarkProcessedRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentId': value.contentId,
        'userId': value.userId,
    };
}

