/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetamaskCircleUSDCEntryRequestDto
 */
export interface MetamaskCircleUSDCEntryRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MetamaskCircleUSDCEntryRequestDto
     */
    payinId: string;
}

export function MetamaskCircleUSDCEntryRequestDtoFromJSON(json: any): MetamaskCircleUSDCEntryRequestDto {
    return MetamaskCircleUSDCEntryRequestDtoFromJSONTyped(json, false);
}

export function MetamaskCircleUSDCEntryRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetamaskCircleUSDCEntryRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payinId': json['payinId'],
    };
}

export function MetamaskCircleUSDCEntryRequestDtoToJSON(value?: MetamaskCircleUSDCEntryRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payinId': value.payinId,
    };
}

