/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MintPassRequestDto
 */
export interface MintPassRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MintPassRequestDto
     */
    passId: string;
}

/**
 * Check if a given object implements the MintPassRequestDto interface.
 */
export function instanceOfMintPassRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "passId" in value;

    return isInstance;
}

export function MintPassRequestDtoFromJSON(json: any): MintPassRequestDto {
    return MintPassRequestDtoFromJSONTyped(json, false);
}

export function MintPassRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintPassRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'passId': json['passId'],
    };
}

export function MintPassRequestDtoToJSON(value?: MintPassRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'passId': value.passId,
    };
}

