/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MintPassResponseDto
 */
export interface MintPassResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof MintPassResponseDto
     */
    minted: boolean;
}

/**
 * Check if a given object implements the MintPassResponseDto interface.
 */
export function instanceOfMintPassResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "minted" in value;

    return isInstance;
}

export function MintPassResponseDtoFromJSON(json: any): MintPassResponseDto {
    return MintPassResponseDtoFromJSONTyped(json, false);
}

export function MintPassResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintPassResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minted': json['minted'],
    };
}

export function MintPassResponseDtoToJSON(value?: MintPassResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'minted': value.minted,
    };
}

