/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentBareDto } from './ContentBareDto';
import {
    ContentBareDtoFromJSON,
    ContentBareDtoFromJSONTyped,
    ContentBareDtoToJSON,
} from './ContentBareDto';

/**
 * 
 * @export
 * @interface PaidMessageDto
 */
export interface PaidMessageDto {
    /**
     * 
     * @type {string}
     * @memberof PaidMessageDto
     */
    paidMessageId: string;
    /**
     * 
     * @type {string}
     * @memberof PaidMessageDto
     */
    creatorId: string;
    /**
     * 
     * @type {string}
     * @memberof PaidMessageDto
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    price: number;
    /**
     * 
     * @type {Array<ContentBareDto>}
     * @memberof PaidMessageDto
     */
    bareContents: Array<ContentBareDto>;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    previewIndex: number;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    numPurchases: number;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    earningsPurchases: number;
    /**
     * 
     * @type {Date}
     * @memberof PaidMessageDto
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PaidMessageDto
     */
    isWelcomeMesage: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PaidMessageDto
     */
    unsentAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PaidMessageDto
     */
    hiddenAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    sentTo: number;
}

/**
 * Check if a given object implements the PaidMessageDto interface.
 */
export function instanceOfPaidMessageDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "paidMessageId" in value;
    isInstance = isInstance && "creatorId" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "bareContents" in value;
    isInstance = isInstance && "previewIndex" in value;
    isInstance = isInstance && "numPurchases" in value;
    isInstance = isInstance && "earningsPurchases" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "isWelcomeMesage" in value;
    isInstance = isInstance && "unsentAt" in value;
    isInstance = isInstance && "hiddenAt" in value;
    isInstance = isInstance && "sentTo" in value;

    return isInstance;
}

export function PaidMessageDtoFromJSON(json: any): PaidMessageDto {
    return PaidMessageDtoFromJSONTyped(json, false);
}

export function PaidMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaidMessageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paidMessageId': json['paidMessageId'],
        'creatorId': json['creatorId'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'price': json['price'],
        'bareContents': ((json['bareContents'] as Array<any>).map(ContentBareDtoFromJSON)),
        'previewIndex': json['previewIndex'],
        'numPurchases': json['numPurchases'],
        'earningsPurchases': json['earningsPurchases'],
        'createdAt': (new Date(json['createdAt'])),
        'isWelcomeMesage': json['isWelcomeMesage'],
        'unsentAt': (json['unsentAt'] === null ? null : new Date(json['unsentAt'])),
        'hiddenAt': (json['hiddenAt'] === null ? null : new Date(json['hiddenAt'])),
        'sentTo': json['sentTo'],
    };
}

export function PaidMessageDtoToJSON(value?: PaidMessageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paidMessageId': value.paidMessageId,
        'creatorId': value.creatorId,
        'text': value.text,
        'price': value.price,
        'bareContents': ((value.bareContents as Array<any>).map(ContentBareDtoToJSON)),
        'previewIndex': value.previewIndex,
        'numPurchases': value.numPurchases,
        'earningsPurchases': value.earningsPurchases,
        'createdAt': (value.createdAt.toISOString()),
        'isWelcomeMesage': value.isWelcomeMesage,
        'unsentAt': (value.unsentAt === null ? null : value.unsentAt.toISOString()),
        'hiddenAt': (value.hiddenAt === null ? null : value.hiddenAt.toISOString()),
        'sentTo': value.sentTo,
    };
}

