/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaidMessageDto
 */
export interface PaidMessageDto {
    /**
     * 
     * @type {string}
     * @memberof PaidMessageDto
     */
    paidMessageId: string;
    /**
     * 
     * @type {string}
     * @memberof PaidMessageDto
     */
    creatorId: string;
    /**
     * 
     * @type {string}
     * @memberof PaidMessageDto
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    price: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaidMessageDto
     */
    contentIds: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    numPurchases: number;
    /**
     * 
     * @type {number}
     * @memberof PaidMessageDto
     */
    earningsPurchases: number;
    /**
     * 
     * @type {Date}
     * @memberof PaidMessageDto
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PaidMessageDto interface.
 */
export function instanceOfPaidMessageDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "paidMessageId" in value;
    isInstance = isInstance && "creatorId" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "contentIds" in value;
    isInstance = isInstance && "numPurchases" in value;
    isInstance = isInstance && "earningsPurchases" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function PaidMessageDtoFromJSON(json: any): PaidMessageDto {
    return PaidMessageDtoFromJSONTyped(json, false);
}

export function PaidMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaidMessageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paidMessageId': json['paidMessageId'],
        'creatorId': json['creatorId'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'price': json['price'],
        'contentIds': json['contentIds'],
        'numPurchases': json['numPurchases'],
        'earningsPurchases': json['earningsPurchases'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function PaidMessageDtoToJSON(value?: PaidMessageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paidMessageId': value.paidMessageId,
        'creatorId': value.creatorId,
        'text': value.text,
        'price': value.price,
        'contentIds': value.contentIds,
        'numPurchases': value.numPurchases,
        'earningsPurchases': value.earningsPurchases,
        'createdAt': (value.createdAt.toISOString()),
    };
}

