/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PassDto
 */
export interface PassDto {
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    creatorId: string;
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    type: PassDtoTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof PassDto
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof PassDto
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof PassDto
     */
    totalSupply: number;
    /**
     * 
     * @type {number}
     * @memberof PassDto
     */
    remainingSupply: number;
    /**
     * 
     * @type {boolean}
     * @memberof PassDto
     */
    freetrial: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PassDto
     */
    pinnedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PassDto
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    creatorUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof PassDto
     */
    creatorDisplayName?: string;
}


/**
 * @export
 */
export const PassDtoTypeEnum = {
    Subscription: 'subscription',
    Lifetime: 'lifetime',
    External: 'external'
} as const;
export type PassDtoTypeEnum = typeof PassDtoTypeEnum[keyof typeof PassDtoTypeEnum];


export function PassDtoFromJSON(json: any): PassDto {
    return PassDtoFromJSONTyped(json, false);
}

export function PassDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'creatorId': json['creatorId'],
        'title': json['title'],
        'description': json['description'],
        'type': json['type'],
        'price': json['price'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'totalSupply': json['totalSupply'],
        'remainingSupply': json['remainingSupply'],
        'freetrial': json['freetrial'],
        'pinnedAt': !exists(json, 'pinnedAt') ? undefined : (new Date(json['pinnedAt'])),
        'expiresAt': !exists(json, 'expiresAt') ? undefined : (new Date(json['expiresAt'])),
        'creatorUsername': !exists(json, 'creatorUsername') ? undefined : json['creatorUsername'],
        'creatorDisplayName': !exists(json, 'creatorDisplayName') ? undefined : json['creatorDisplayName'],
    };
}

export function PassDtoToJSON(value?: PassDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'creatorId': value.creatorId,
        'title': value.title,
        'description': value.description,
        'type': value.type,
        'price': value.price,
        'duration': value.duration,
        'totalSupply': value.totalSupply,
        'remainingSupply': value.remainingSupply,
        'freetrial': value.freetrial,
        'pinnedAt': value.pinnedAt === undefined ? undefined : (value.pinnedAt.toISOString()),
        'expiresAt': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
        'creatorUsername': value.creatorUsername,
        'creatorDisplayName': value.creatorDisplayName,
    };
}

