/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayinMethodDto
 */
export interface PayinMethodDto {
    /**
     * 
     * @type {string}
     * @memberof PayinMethodDto
     */
    methodId?: string;
    /**
     * 
     * @type {string}
     * @memberof PayinMethodDto
     */
    method: PayinMethodDtoMethodEnum;
}


/**
 * @export
 */
export const PayinMethodDtoMethodEnum = {
    CircleCard: 'CIRCLE_CARD',
    PhantomCircleUsdc: 'PHANTOM_CIRCLE_USDC',
    MetamaskCircleUsdc: 'METAMASK_CIRCLE_USDC',
    MetamaskCircleEth: 'METAMASK_CIRCLE_ETH'
} as const;
export type PayinMethodDtoMethodEnum = typeof PayinMethodDtoMethodEnum[keyof typeof PayinMethodDtoMethodEnum];


export function PayinMethodDtoFromJSON(json: any): PayinMethodDto {
    return PayinMethodDtoFromJSONTyped(json, false);
}

export function PayinMethodDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayinMethodDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'methodId': !exists(json, 'methodId') ? undefined : json['methodId'],
        'method': json['method'],
    };
}

export function PayinMethodDtoToJSON(value?: PayinMethodDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'methodId': value.methodId,
        'method': value.method,
    };
}

