/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostHistoryDto
 */
export interface PostHistoryDto {
    /**
     * 
     * @type {string}
     * @memberof PostHistoryDto
     */
    postId: string;
    /**
     * 
     * @type {number}
     * @memberof PostHistoryDto
     */
    numLikes: number;
    /**
     * 
     * @type {number}
     * @memberof PostHistoryDto
     */
    numComments: number;
    /**
     * 
     * @type {number}
     * @memberof PostHistoryDto
     */
    numPurchases: number;
    /**
     * 
     * @type {number}
     * @memberof PostHistoryDto
     */
    earningsPurchases: number;
    /**
     * 
     * @type {number}
     * @memberof PostHistoryDto
     */
    totalTipAmount?: number;
}

/**
 * Check if a given object implements the PostHistoryDto interface.
 */
export function instanceOfPostHistoryDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "postId" in value;
    isInstance = isInstance && "numLikes" in value;
    isInstance = isInstance && "numComments" in value;
    isInstance = isInstance && "numPurchases" in value;
    isInstance = isInstance && "earningsPurchases" in value;

    return isInstance;
}

export function PostHistoryDtoFromJSON(json: any): PostHistoryDto {
    return PostHistoryDtoFromJSONTyped(json, false);
}

export function PostHistoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostHistoryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'numLikes': json['numLikes'],
        'numComments': json['numComments'],
        'numPurchases': json['numPurchases'],
        'earningsPurchases': json['earningsPurchases'],
        'totalTipAmount': !exists(json, 'totalTipAmount') ? undefined : json['totalTipAmount'],
    };
}

export function PostHistoryDtoToJSON(value?: PostHistoryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postId': value.postId,
        'numLikes': value.numLikes,
        'numComments': value.numComments,
        'numPurchases': value.numPurchases,
        'earningsPurchases': value.earningsPurchases,
        'totalTipAmount': value.totalTipAmount,
    };
}

