/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshAuthTokenRequestDto
 */
export interface RefreshAuthTokenRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RefreshAuthTokenRequestDto
     */
    refreshToken: string;
}

export function RefreshAuthTokenRequestDtoFromJSON(json: any): RefreshAuthTokenRequestDto {
    return RefreshAuthTokenRequestDtoFromJSONTyped(json, false);
}

export function RefreshAuthTokenRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshAuthTokenRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshAuthTokenRequestDtoToJSON(value?: RefreshAuthTokenRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refreshToken': value.refreshToken,
    };
}

