/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterPayinResponseDto
 */
export interface RegisterPayinResponseDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterPayinResponseDto
     */
    payinId: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterPayinResponseDto
     */
    method: RegisterPayinResponseDtoMethodEnum;
    /**
     * 
     * @type {number}
     * @memberof RegisterPayinResponseDto
     */
    amount: number;
}


/**
 * @export
 */
export const RegisterPayinResponseDtoMethodEnum = {
    CircleCard: 'circle_card',
    PhantomCircleUsdc: 'phantom_circle_usdc',
    MetamaskCircleUsdc: 'metamask_circle_usdc',
    MetamaskCircleEth: 'metamask_circle_eth'
} as const;
export type RegisterPayinResponseDtoMethodEnum = typeof RegisterPayinResponseDtoMethodEnum[keyof typeof RegisterPayinResponseDtoMethodEnum];


export function RegisterPayinResponseDtoFromJSON(json: any): RegisterPayinResponseDto {
    return RegisterPayinResponseDtoFromJSONTyped(json, false);
}

export function RegisterPayinResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterPayinResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payinId': json['payinId'],
        'method': json['method'],
        'amount': json['amount'],
    };
}

export function RegisterPayinResponseDtoToJSON(value?: RegisterPayinResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payinId': value.payinId,
        'method': value.method,
        'amount': value.amount,
    };
}

