/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PayinMethodDto,
    PayinMethodDtoFromJSON,
    PayinMethodDtoFromJSONTyped,
    PayinMethodDtoToJSON,
} from './PayinMethodDto';

/**
 * 
 * @export
 * @interface RenewPassHolderDto
 */
export interface RenewPassHolderDto {
    /**
     * 
     * @type {string}
     * @memberof RenewPassHolderDto
     */
    passOwnershipId: string;
    /**
     * 
     * @type {PayinMethodDto}
     * @memberof RenewPassHolderDto
     */
    payinMethod?: PayinMethodDto;
}

export function RenewPassHolderDtoFromJSON(json: any): RenewPassHolderDto {
    return RenewPassHolderDtoFromJSONTyped(json, false);
}

export function RenewPassHolderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenewPassHolderDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'passOwnershipId': json['passOwnershipId'],
        'payinMethod': !exists(json, 'payinMethod') ? undefined : PayinMethodDtoFromJSON(json['payinMethod']),
    };
}

export function RenewPassHolderDtoToJSON(value?: RenewPassHolderDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'passOwnershipId': value.passOwnershipId,
        'payinMethod': PayinMethodDtoToJSON(value.payinMethod),
    };
}

