/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceDto
 */
export interface SourceDto {
    /**
     * 
     * @type {string}
     * @memberof SourceDto
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SourceDto
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceDto
     */
    chain?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceDto
     */
    id?: string;
}

export function SourceDtoFromJSON(json: any): SourceDto {
    return SourceDtoFromJSONTyped(json, false);
}

export function SourceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'chain': !exists(json, 'chain') ? undefined : json['chain'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function SourceDtoToJSON(value?: SourceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'address': value.address,
        'chain': value.chain,
        'id': value.id,
    };
}

