/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitPersonaInquiryRequestDto
 */
export interface SubmitPersonaInquiryRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SubmitPersonaInquiryRequestDto
     */
    personaId: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitPersonaInquiryRequestDto
     */
    personaStatus: SubmitPersonaInquiryRequestDtoPersonaStatusEnum;
}


/**
 * @export
 */
export const SubmitPersonaInquiryRequestDtoPersonaStatusEnum = {
    Created: 'created',
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed',
    Expired: 'expired',
    NeedsReview: 'needs_review',
    Approved: 'approved',
    Declined: 'declined'
} as const;
export type SubmitPersonaInquiryRequestDtoPersonaStatusEnum = typeof SubmitPersonaInquiryRequestDtoPersonaStatusEnum[keyof typeof SubmitPersonaInquiryRequestDtoPersonaStatusEnum];


export function SubmitPersonaInquiryRequestDtoFromJSON(json: any): SubmitPersonaInquiryRequestDto {
    return SubmitPersonaInquiryRequestDtoFromJSONTyped(json, false);
}

export function SubmitPersonaInquiryRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitPersonaInquiryRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'personaId': json['personaId'],
        'personaStatus': json['personaStatus'],
    };
}

export function SubmitPersonaInquiryRequestDtoToJSON(value?: SubmitPersonaInquiryRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'personaId': value.personaId,
        'personaStatus': value.personaStatus,
    };
}

