/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePassRequestDto
 */
export interface UpdatePassRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePassRequestDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePassRequestDto
     */
    description: string;
}

/**
 * Check if a given object implements the UpdatePassRequestDto interface.
 */
export function instanceOfUpdatePassRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function UpdatePassRequestDtoFromJSON(json: any): UpdatePassRequestDto {
    return UpdatePassRequestDtoFromJSONTyped(json, false);
}

export function UpdatePassRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePassRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
    };
}

export function UpdatePassRequestDtoToJSON(value?: UpdatePassRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
    };
}

