/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUsernameRequestDto
 */
export interface UpdateUsernameRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateUsernameRequestDto
     */
    username: string;
}

export function UpdateUsernameRequestDtoFromJSON(json: any): UpdateUsernameRequestDto {
    return UpdateUsernameRequestDtoFromJSONTyped(json, false);
}

export function UpdateUsernameRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUsernameRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function UpdateUsernameRequestDtoToJSON(value?: UpdateUsernameRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

