/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateExternalPassRequestDto
 */
export interface UpdateExternalPassRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    secret: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    chain: UpdateExternalPassRequestDtoChainEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateExternalPassRequestDto
     */
    passId: string;
}


/**
 * @export
 */
export const UpdateExternalPassRequestDtoChainEnum = {
    Eth: 'eth',
    Sol: 'sol',
    Avax: 'avax',
    Matic: 'matic'
} as const;
export type UpdateExternalPassRequestDtoChainEnum = typeof UpdateExternalPassRequestDtoChainEnum[keyof typeof UpdateExternalPassRequestDtoChainEnum];


/**
 * Check if a given object implements the UpdateExternalPassRequestDto interface.
 */
export function instanceOfUpdateExternalPassRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "secret" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "chain" in value;
    isInstance = isInstance && "passId" in value;

    return isInstance;
}

export function UpdateExternalPassRequestDtoFromJSON(json: any): UpdateExternalPassRequestDto {
    return UpdateExternalPassRequestDtoFromJSONTyped(json, false);
}

export function UpdateExternalPassRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateExternalPassRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'secret': json['secret'],
        'title': json['title'],
        'description': json['description'],
        'chain': json['chain'],
        'passId': json['passId'],
    };
}

export function UpdateExternalPassRequestDtoToJSON(value?: UpdateExternalPassRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'username': value.username,
        'secret': value.secret,
        'title': value.title,
        'description': value.description,
        'chain': value.chain,
        'passId': value.passId,
    };
}

