/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePassDto
 */
export interface UpdatePassDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePassDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePassDto
     */
    description: string;
}

export function UpdatePassDtoFromJSON(json: any): UpdatePassDto {
    return UpdatePassDtoFromJSONTyped(json, false);
}

export function UpdatePassDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePassDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
    };
}

export function UpdatePassDtoToJSON(value?: UpdatePassDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
    };
}

