/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateScheduledTimeRequestDto
 */
export interface UpdateScheduledTimeRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateScheduledTimeRequestDto
     */
    scheduledEventId: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateScheduledTimeRequestDto
     */
    scheduledAt: Date;
}

/**
 * Check if a given object implements the UpdateScheduledTimeRequestDto interface.
 */
export function instanceOfUpdateScheduledTimeRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "scheduledEventId" in value;
    isInstance = isInstance && "scheduledAt" in value;

    return isInstance;
}

export function UpdateScheduledTimeRequestDtoFromJSON(json: any): UpdateScheduledTimeRequestDto {
    return UpdateScheduledTimeRequestDtoFromJSONTyped(json, false);
}

export function UpdateScheduledTimeRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateScheduledTimeRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scheduledEventId': json['scheduledEventId'],
        'scheduledAt': (new Date(json['scheduledAt'])),
    };
}

export function UpdateScheduledTimeRequestDtoToJSON(value?: UpdateScheduledTimeRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scheduledEventId': value.scheduledEventId,
        'scheduledAt': (value.scheduledAt.toISOString()),
    };
}

