/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileDto
 */
export interface UpdateProfileDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    coverTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    coverDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    profileImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    profileCoverImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    instagramUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    tiktokUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    youtubeUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    discordUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    twitchUrl?: string;
}

export function UpdateProfileDtoFromJSON(json: any): UpdateProfileDto {
    return UpdateProfileDtoFromJSONTyped(json, false);
}

export function UpdateProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'coverTitle': !exists(json, 'coverTitle') ? undefined : json['coverTitle'],
        'coverDescription': !exists(json, 'coverDescription') ? undefined : json['coverDescription'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'profileImageUrl': !exists(json, 'profileImageUrl') ? undefined : json['profileImageUrl'],
        'profileCoverImageUrl': !exists(json, 'profileCoverImageUrl') ? undefined : json['profileCoverImageUrl'],
        'instagramUrl': !exists(json, 'instagramUrl') ? undefined : json['instagramUrl'],
        'tiktokUrl': !exists(json, 'tiktokUrl') ? undefined : json['tiktokUrl'],
        'youtubeUrl': !exists(json, 'youtubeUrl') ? undefined : json['youtubeUrl'],
        'discordUrl': !exists(json, 'discordUrl') ? undefined : json['discordUrl'],
        'twitchUrl': !exists(json, 'twitchUrl') ? undefined : json['twitchUrl'],
    };
}

export function UpdateProfileDtoToJSON(value?: UpdateProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'displayName': value.displayName,
        'coverTitle': value.coverTitle,
        'coverDescription': value.coverDescription,
        'description': value.description,
        'profileImageUrl': value.profileImageUrl,
        'profileCoverImageUrl': value.profileCoverImageUrl,
        'instagramUrl': value.instagramUrl,
        'tiktokUrl': value.tiktokUrl,
        'youtubeUrl': value.youtubeUrl,
        'discordUrl': value.discordUrl,
        'twitchUrl': value.twitchUrl,
    };
}

