/* tslint:disable */
/* eslint-disable */
/**
 * Moment Backend
 * Be in the moment
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    oauthId: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    oauthProvider: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    birthday: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    isKYCVerified: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    isCreator: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    isDisabled: boolean;
}

export function UserDtoFromJSON(json: any): UserDto {
    return UserDtoFromJSONTyped(json, false);
}

export function UserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'oauthId': json['oauthId'],
        'oauthProvider': json['oauthProvider'],
        'userName': json['userName'],
        'fullName': json['fullName'],
        'phoneNumber': json['phoneNumber'],
        'birthday': json['birthday'],
        'isKYCVerified': json['isKYCVerified'],
        'isCreator': json['isCreator'],
        'isDisabled': json['isDisabled'],
    };
}

export function UserDtoToJSON(value?: UserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'oauthId': value.oauthId,
        'oauthProvider': value.oauthProvider,
        'userName': value.userName,
        'fullName': value.fullName,
        'phoneNumber': value.phoneNumber,
        'birthday': value.birthday,
        'isKYCVerified': value.isKYCVerified,
        'isCreator': value.isCreator,
        'isDisabled': value.isDisabled,
    };
}

