export const FOLLOWER_NOT_EXIST = 'Follower does not exist'
export const CREATOR_NOT_EXIST = 'Creator does not exist'
export const IS_NOT_CREATOR = 'Cannot subscribe to non-creator'
export const FOLLOWING_NOT_EXIST = 'Following does not exist'
export const FOLLOWING_ALREADY_EXIST = 'Following already exists'
