export const PROFILE_DISPLAY_NAME_LENGTH = 100
export const PROFILE_COVER_TITLE_LENGTH = 100
export const PROFILE_COVER_DESCRIPTION_LENGTH = 250
export const PROFILE_DESCRIPTION_LENGTH = 500
export const PROFILE_EXTERNAL_URL_LENGTH = 256
