/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class AuthTwitterApi extends runtime.BaseAPI {

    /**
     * Start the twitter oauth flow
     */
    async twitterOauthTwitterAuthRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/auth/twitter`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start the twitter oauth flow
     */
    async twitterOauthTwitterAuth(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.twitterOauthTwitterAuthRaw(initOverrides);
    }

    /**
     * Redirect from twitter oauth flow
     */
    async twitterOauthTwitterAuthRedirectRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/auth/twitter/redirect`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Redirect from twitter oauth flow
     */
    async twitterOauthTwitterAuthRedirect(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.twitterOauthTwitterAuthRedirectRaw(initOverrides);
    }

}
