/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GetCreatorSettingsResponseDto,
    GetCreatorSettingsResponseDtoFromJSON,
    GetCreatorSettingsResponseDtoToJSON,
    UpdateCreatorSettingsRequestDto,
    UpdateCreatorSettingsRequestDtoFromJSON,
    UpdateCreatorSettingsRequestDtoToJSON,
} from '../models';

export interface UpdateCreatorSettingsRequest {
    updateCreatorSettingsRequestDto: UpdateCreatorSettingsRequestDto;
}

/**
 * 
 */
export class CreatorSettingsApi extends runtime.BaseAPI {

    /**
     * Gets creator settings
     */
    async getCreatorSettingsRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GetCreatorSettingsResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/creator-settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCreatorSettingsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Gets creator settings
     */
    async getCreatorSettings(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GetCreatorSettingsResponseDto> {
        const response = await this.getCreatorSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Updates creator settings
     */
    async updateCreatorSettingsRaw(requestParameters: UpdateCreatorSettingsRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.updateCreatorSettingsRequestDto === null || requestParameters.updateCreatorSettingsRequestDto === undefined) {
            throw new runtime.RequiredError('updateCreatorSettingsRequestDto','Required parameter requestParameters.updateCreatorSettingsRequestDto was null or undefined when calling updateCreatorSettings.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/creator-settings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCreatorSettingsRequestDtoToJSON(requestParameters.updateCreatorSettingsRequestDto),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Updates creator settings
     */
    async updateCreatorSettings(requestParameters: UpdateCreatorSettingsRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<boolean> {
        const response = await this.updateCreatorSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
