/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateEthNftCollectionDto,
    CreateEthNftCollectionDtoFromJSON,
    CreateEthNftCollectionDtoToJSON,
} from '../models';

export interface EthCreateNftCollectionRequest {
    createEthNftCollectionDto: CreateEthNftCollectionDto;
}

/**
 * 
 */
export class EthApi extends runtime.BaseAPI {

    /**
     * Creates ETH NFT Collection
     */
    async ethCreateNftCollectionRaw(requestParameters: EthCreateNftCollectionRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<CreateEthNftCollectionDto>> {
        if (requestParameters.createEthNftCollectionDto === null || requestParameters.createEthNftCollectionDto === undefined) {
            throw new runtime.RequiredError('createEthNftCollectionDto','Required parameter requestParameters.createEthNftCollectionDto was null or undefined when calling ethCreateNftCollection.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/eth/nftcollection`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEthNftCollectionDtoToJSON(requestParameters.createEthNftCollectionDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEthNftCollectionDtoFromJSON(jsonValue));
    }

    /**
     * Creates ETH NFT Collection
     */
    async ethCreateNftCollection(requestParameters: EthCreateNftCollectionRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<CreateEthNftCollectionDto> {
        const response = await this.ethCreateNftCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
