/* tslint:disable */
/* eslint-disable */
/**
 * Passes Backend
 * Get your pass
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreatePassDto,
    CreatePassDtoFromJSON,
    CreatePassDtoToJSON,
    CreatePassHolderDto,
    CreatePassHolderDtoFromJSON,
    CreatePassHolderDtoToJSON,
    GetPassDto,
    GetPassDtoFromJSON,
    GetPassDtoToJSON,
    PayinDataDto,
    PayinDataDtoFromJSON,
    PayinDataDtoToJSON,
    RegisterPayinResponseDto,
    RegisterPayinResponseDtoFromJSON,
    RegisterPayinResponseDtoToJSON,
    RenewPassHolderDto,
    RenewPassHolderDtoFromJSON,
    RenewPassHolderDtoToJSON,
    UpdatePassDto,
    UpdatePassDtoFromJSON,
    UpdatePassDtoToJSON,
} from '../models';

export interface PassCreateRequest {
    createPassDto: CreatePassDto;
}

export interface PassFindOneRequest {
    id: string;
}

export interface PassGetCreatorPassesRequest {
    creatorId: string;
}

export interface PassGetOwnedPassesRequest {
    creatorId: string;
}

export interface PassRegisterCreatePassRequest {
    createPassHolderDto: CreatePassHolderDto;
}

export interface PassRegisterCreatePassDataRequest {
    createPassHolderDto: CreatePassHolderDto;
}

export interface PassRegisterRenewPassRequest {
    renewPassHolderDto: RenewPassHolderDto;
}

export interface PassRegisterRenewPassDataRequest {
    renewPassHolderDto: RenewPassHolderDto;
}

export interface PassUpdateRequest {
    id: string;
    updatePassDto: UpdatePassDto;
}

/**
 * 
 */
export class PassApi extends runtime.BaseAPI {

    /**
     * Creates a pass
     */
    async passCreateRaw(requestParameters: PassCreateRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GetPassDto>> {
        if (requestParameters.createPassDto === null || requestParameters.createPassDto === undefined) {
            throw new runtime.RequiredError('createPassDto','Required parameter requestParameters.createPassDto was null or undefined when calling passCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pass`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePassDtoToJSON(requestParameters.createPassDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPassDtoFromJSON(jsonValue));
    }

    /**
     * Creates a pass
     */
    async passCreate(requestParameters: PassCreateRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GetPassDto> {
        const response = await this.passCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a pass
     */
    async passFindOneRaw(requestParameters: PassFindOneRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GetPassDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling passFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/pass/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPassDtoFromJSON(jsonValue));
    }

    /**
     * Gets a pass
     */
    async passFindOne(requestParameters: PassFindOneRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GetPassDto> {
        const response = await this.passFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets passes created by a creator
     */
    async passGetCreatorPassesRaw(requestParameters: PassGetCreatorPassesRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<GetPassDto>>> {
        if (requestParameters.creatorId === null || requestParameters.creatorId === undefined) {
            throw new runtime.RequiredError('creatorId','Required parameter requestParameters.creatorId was null or undefined when calling passGetCreatorPasses.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/pass/created/{creatorId}`.replace(`{${"creatorId"}}`, encodeURIComponent(String(requestParameters.creatorId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetPassDtoFromJSON));
    }

    /**
     * Gets passes created by a creator
     */
    async passGetCreatorPasses(requestParameters: PassGetCreatorPassesRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<GetPassDto>> {
        const response = await this.passGetCreatorPassesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets passes held by user
     */
    async passGetOwnedPassesRaw(requestParameters: PassGetOwnedPassesRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<GetPassDto>>> {
        if (requestParameters.creatorId === null || requestParameters.creatorId === undefined) {
            throw new runtime.RequiredError('creatorId','Required parameter requestParameters.creatorId was null or undefined when calling passGetOwnedPasses.');
        }

        const queryParameters: any = {};

        if (requestParameters.creatorId !== undefined) {
            queryParameters['creatorId'] = requestParameters.creatorId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/pass/owned`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetPassDtoFromJSON));
    }

    /**
     * Gets passes held by user
     */
    async passGetOwnedPasses(requestParameters: PassGetOwnedPassesRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<GetPassDto>> {
        const response = await this.passGetOwnedPassesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register create pass payin
     */
    async passRegisterCreatePassRaw(requestParameters: PassRegisterCreatePassRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<RegisterPayinResponseDto>> {
        if (requestParameters.createPassHolderDto === null || requestParameters.createPassHolderDto === undefined) {
            throw new runtime.RequiredError('createPassHolderDto','Required parameter requestParameters.createPassHolderDto was null or undefined when calling passRegisterCreatePass.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pass/pay/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePassHolderDtoToJSON(requestParameters.createPassHolderDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterPayinResponseDtoFromJSON(jsonValue));
    }

    /**
     * Register create pass payin
     */
    async passRegisterCreatePass(requestParameters: PassRegisterCreatePassRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<RegisterPayinResponseDto> {
        const response = await this.passRegisterCreatePassRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get register create pass data
     */
    async passRegisterCreatePassDataRaw(requestParameters: PassRegisterCreatePassDataRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<PayinDataDto>> {
        if (requestParameters.createPassHolderDto === null || requestParameters.createPassHolderDto === undefined) {
            throw new runtime.RequiredError('createPassHolderDto','Required parameter requestParameters.createPassHolderDto was null or undefined when calling passRegisterCreatePassData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pass/pay/data/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePassHolderDtoToJSON(requestParameters.createPassHolderDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PayinDataDtoFromJSON(jsonValue));
    }

    /**
     * Get register create pass data
     */
    async passRegisterCreatePassData(requestParameters: PassRegisterCreatePassDataRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<PayinDataDto> {
        const response = await this.passRegisterCreatePassDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register renew pass payin
     */
    async passRegisterRenewPassRaw(requestParameters: PassRegisterRenewPassRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<RegisterPayinResponseDto>> {
        if (requestParameters.renewPassHolderDto === null || requestParameters.renewPassHolderDto === undefined) {
            throw new runtime.RequiredError('renewPassHolderDto','Required parameter requestParameters.renewPassHolderDto was null or undefined when calling passRegisterRenewPass.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pass/pay/renew`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenewPassHolderDtoToJSON(requestParameters.renewPassHolderDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterPayinResponseDtoFromJSON(jsonValue));
    }

    /**
     * Register renew pass payin
     */
    async passRegisterRenewPass(requestParameters: PassRegisterRenewPassRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<RegisterPayinResponseDto> {
        const response = await this.passRegisterRenewPassRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get register renew pass data
     */
    async passRegisterRenewPassDataRaw(requestParameters: PassRegisterRenewPassDataRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<PayinDataDto>> {
        if (requestParameters.renewPassHolderDto === null || requestParameters.renewPassHolderDto === undefined) {
            throw new runtime.RequiredError('renewPassHolderDto','Required parameter requestParameters.renewPassHolderDto was null or undefined when calling passRegisterRenewPassData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pass/pay/data/renew`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenewPassHolderDtoToJSON(requestParameters.renewPassHolderDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PayinDataDtoFromJSON(jsonValue));
    }

    /**
     * Get register renew pass data
     */
    async passRegisterRenewPassData(requestParameters: PassRegisterRenewPassDataRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<PayinDataDto> {
        const response = await this.passRegisterRenewPassDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a pass
     */
    async passUpdateRaw(requestParameters: PassUpdateRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GetPassDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling passUpdate.');
        }

        if (requestParameters.updatePassDto === null || requestParameters.updatePassDto === undefined) {
            throw new runtime.RequiredError('updatePassDto','Required parameter requestParameters.updatePassDto was null or undefined when calling passUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pass/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePassDtoToJSON(requestParameters.updatePassDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPassDtoFromJSON(jsonValue));
    }

    /**
     * Updates a pass
     */
    async passUpdate(requestParameters: PassUpdateRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GetPassDto> {
        const response = await this.passUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
