export const MIN_TIP_MESSAGE_PRICE = 3
export const MAX_TIP_MESSAGE_PRICE = 1000

export const MIN_PAID_MESSAGE_PRICE = 3
export const MAX_PAID_MESSAGE_PRICE = 5000

export const MAX_MESSAGE_LENGTH = 10000
