export const MAX_SCHEDULE_DURATION_IN_MONTHS = 6

export const SCHEDULER_VIEWABLE_THIS_MANY_MONTHS_AGO = 24
export const SCHEDULER_VIEWABLE_THIS_MANY_MONTHS_IN_FUTURE =
  MAX_SCHEDULE_DURATION_IN_MONTHS

export const SCHEDULE_MINUTE_LIMIT = 10
