name: Linting

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - staging
      - production

jobs:

  lint-api:
    name: Lint @moment/api package
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn workspace @moment/api prettier:check
      - run: yarn workspace @moment/api lint:check
      - run: yarn workspace @moment/api ts:check

  lint-ui:
    name: Lint @moment/ui package
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn workspace @moment/ui prettier:check
      - run: yarn workspace @moment/ui lint:check
      - run: yarn workspace @moment/ui ts:check

  check-api-configs:
    name: Check @moment/api configs
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout monorepo code
        uses: actions/checkout@v2
        with:
          path: monorepo
      - name: Checkout infra code
        uses: actions/checkout@v2
        with:
          repository: buildmoment/infra
          ref: main
          token: ${{ secrets.INFRA_REPO_ACCESS }}
          path: infra
      - run: ./monorepo/bin/config-check.sh
