name: Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - staging
      - production

jobs:

  # UI (frontend)

  ui-lint:
    name: Lint @passes/ui package
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: ./packages/ui/bin/lint.sh
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @passes/ui prettier:check
      - run: yarn workspace @passes/ui lint:check
      - run: yarn workspace @passes/ui ts:check

  ui-test:
    name: Test @passes/ui package
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @passes/ui build

  # API (backend)

  api-lint:
    name: Lint @passes/api package
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @passes/api prettier:check
      - run: yarn workspace @passes/api lint:check
      - run: yarn workspace @passes/api ts:check

  api-test:
    name: Test @passes/api package
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @passes/api test

  api-check-configs:
    name: Check @passes/api configs
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout monorepo code
        uses: actions/checkout@v3
        with:
          path: monorepo
      - name: Checkout infra code
        uses: actions/checkout@v3
        with:
          repository: getpasses/infra
          ref: main
          token: ${{ secrets.INFRA_REPO_ACCESS }}
          path: infra
      - run: ./monorepo/bin/config-check.sh

  api-compatibility:
    name: Check @passes/api API compatibility
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: ./bin/api-compatibility.sh
