name: Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:

  test-api:
    name: Test @moment/api package
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn workspace @moment/api test

  test-ui:
    name: Test @moment/ui package
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn workspace @moment/ui build
